# Numpy Exercise

### 1. 
Create a one-dimensional array with range 2 to 5  elements; Create a 2 by 4 two-dimensional array with range 2 to 9; Create a 4 by 3 by 2 three-dimensional array with range 0 to 23.

Print their properties: shape, dimension, size, and data type.

Solution:

In [1]:
import numpy as np

print("Part 1")
a = np.arange(2,6) # one-dimensional array with range 2 to 5 elements
print(a)
print("shape :", a.shape) #shape
print("dimension:", a.ndim) #dimension
print("size:", a.size) #size
print("data-type:", a.dtype) #data type
print()

print("Part 2")
b = np.arange(2,10).reshape(2,4) # 2 by 4 two-dimensional array with range 2 to 9
print(b)
print("shape :", b.shape) #shape
print("dimension:", b.ndim) #dimension
print("size:", b.size) #size
print("data-type:", b.dtype) #data type
print()

print("Part 3")
c = np.arange(0,24).reshape(4,3,2) # 4 by 3 by 2 three-dimensional array with range 0 to 23
print(c)
print("shape :", c.shape) #shape
print("dimension:", c.ndim) #dimension
print("size:", c.size) #size
print("data-type:", c.dtype) #data type

Part 1
[2 3 4 5]
shape : (4,)
dimension: 1
size: 4
data-type: int32

Part 2
[[2 3 4 5]
 [6 7 8 9]]
shape : (2, 4)
dimension: 2
size: 8
data-type: int32

Part 3
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
shape : (4, 3, 2)
dimension: 3
size: 24
data-type: int32


### 2.
Create an array [1, 2, 3, 4] and convert the elements' data type to float. So in printing, it is showing [1., 2., 3., 4.]; 
also, print the reverse order of the array. Finally, change this row vector to a 4 by 1 array.
(Hint: numpy.asfarray() and [::-1], [:, np.newaxis]/[:, -1])

Creat a 5 by 5 array with 1 on the border (first and last row, first and last column) and 0 inside;
(Hint: numpy.ones() and array slicing)

*Create a 3 by 3 array with 1 and add border with 0, as the array will become 5 by 5
(Hint: numpy.pad())

Create a 8 by 8 matrix and fill it with a checkerboard pattern, use 0 to represent white and 1 to represent black.
(Hint: array slicing)


Solution:

In [2]:
print("Part 1")
a = np.arange(1,5) # create array
a = np.asfarray(a) # and convert elements to float
print(a) 
print(a[::-1]) # reverse order of array
print(a[:,np.newaxis]) # change row vector to 4 by 1 array
print()

print("Part 2")
b = np.ones((5,5))
b[1,1:4], b[2,1:4], b[3,1:4] = [0,0,0], [0,0,0], [0,0,0]
print(b)
print()

print("Part 3")
c = np.ones((3,3))
def pad_with(vector, pad_width, iaxis, kwargs):
    pad_value = kwargs.get('padder', 10)
    vector[:pad_width[0]] = pad_value
    vector[-pad_width[1]:] = pad_value
print(np.pad(c, 1, pad_with, padder=0))
print()

print("Part 4")
d = np.zeros((8,8))
for i in range(8):
    if i%2==0:
        for j in range(8):
            if j%2==0:
                d[i][j]=1
    else:
        for j in range(8):
            if j%2!=0:
                d[i][j]=1
print(d)

Part 1
[1. 2. 3. 4.]
[4. 3. 2. 1.]
[[1.]
 [2.]
 [3.]
 [4.]]

Part 2
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Part 3
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

Part 4
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### 3.
Create an array from 0 to 9 and extract the even elements for printing; then replace these elements by -1.
(Hint: use boolean index and element-wise comparison)

Create two arrays: x = [5,6,7,8,3,4] and y = [5,3,4,5,2,4], find the positions of the same elements in the two array.
(Hint: np.where() and element-wise comparison)

Create two arrays: [0, 10, 20, 40, 60] and [0, 40]. test whether each element of x is also present in y.
(Hint: np.isin() and use the two arrays as input)

Solution:

In [3]:
print("Part 1")
a = np.arange(0,10)
print(a)

b = []
for i in a:
    if i % 2 == 0:
        b.append(i) # extract the even elements for printing
        a[i] = -1 # replace these elements by -1

b = np.array(b)        
print(b)    
print(a)
print()

print("Part 2")
x = np.array([5,6,7,8,3,4])
y = np.array([5,3,4,5,2,4])
print(np.where(x == y)) 
print()

print("Part 3")
x = np.array([0, 10, 20, 40, 60])
y = np.array([0, 40])
print(np.isin(x, y)) # test whether each element of x is also present in y

Part 1
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[-1  1 -1  3 -1  5 -1  7 -1  9]

Part 2
(array([0, 5], dtype=int64),)

Part 3
[ True False False  True False]


### 4.
Creat an one-dimensional array to hold 24 random integer numbers between 0 and 100, then do the following:

1. Find the position of minimum and maximum;
2. Reshape it into 6 by 4 array; 
3. Sort the array along axis 0;
4. Calculate mean, average, std of the array along axis = 0;
5. Reshape it into 4 by 3 by 2 and print the new view;
6. Transpose the array in step 5;
7. Save the file into a text output file "data.csv" with the delimiter = ','.
(Hint: x is a 3D array, you can not directly use `np.savetxt` to save it, you have to iterate over the last axis to slice the array and save.)

Solution:

In [4]:
a = np.random.randint(0,100, 24)
print(a)
print()

print("Part 1")
# 1. Find the position of minimum and maximum
print("Postion of min at index =", a.argmin())
print("Postion of max at index =", a.argmax())
print()

print("Part 2")
# 2. Reshape it into 6 by 4 array;
b = a.reshape(6,4)
print(b)
print()

print("Part 3")
# 3. Sort the array along axis 0;
c = np.sort(b, axis=0)
print(c)
print()

print("Part 4")
# 4. Calculate mean, average, std of the array along axis = 0;
print("mean along axis=0 :", c.mean(axis=0))
print("average along axis=0 :", np.average(c, axis=0))
print("std along axis=0 :", c.std(axis=0))
print()

print("Part 5")
# 5. Reshape it into 4 by 3 by 2 and print the new view;
d = c.reshape(4,3,2)
print(d)
print()

print("Part 6")
# 6. Transpose the array in step 5;
e = np.transpose(d)
print(e)
print()

print("Part 7")
# 7. Save the file into a text output file "data.csv" with the delimiter = ','.
#np.savetxt("data.csv", d, delimiter=",")
with open('data.csv', 'w') as savefile:
        for z in range(4):
            np.savetxt(savefile, e[:, :, z], delimiter=",") # iterate over the last axis
            
print("file 'data.csv' created")

[99 47 13 17 58 58 86 41 89 14 80 40 90 64 32 31 49 77 72 92 12 36  3  4]

Part 1
Postion of min at index = 22
Postion of max at index = 0

Part 2
[[99 47 13 17]
 [58 58 86 41]
 [89 14 80 40]
 [90 64 32 31]
 [49 77 72 92]
 [12 36  3  4]]

Part 3
[[12 14  3  4]
 [49 36 13 17]
 [58 47 32 31]
 [89 58 72 40]
 [90 64 80 41]
 [99 77 86 92]]

Part 4
mean along axis=0 : [66.16666667 49.33333333 47.66666667 37.5       ]
average along axis=0 : [66.16666667 49.33333333 47.66666667 37.5       ]
std along axis=0 : [30.17403225 20.36063741 33.03869785 27.60887538]

Part 5
[[[12 14]
  [ 3  4]
  [49 36]]

 [[13 17]
  [58 47]
  [32 31]]

 [[89 58]
  [72 40]
  [90 64]]

 [[80 41]
  [99 77]
  [86 92]]]

Part 6
[[[12 13 89 80]
  [ 3 58 72 99]
  [49 32 90 86]]

 [[14 17 58 41]
  [ 4 47 40 77]
  [36 31 64 92]]]

Part 7
file 'data.csv' created


### 5.
Creat an one-dimensional array with this code:
`a = np.linspace(1,48,48).reshape(3,4,4)`

Index or slice this array to obtain the following:

(a) $20.$

(b) $ [  9. \hspace{0.25em} 10. \hspace{0.25em} 11. \hspace{0.25em}  12.] $

(c) 
$
  [[ 33. \hspace{0.25em} 34. \hspace{0.25em} 35.\hspace{0.25em}  36.] \\
   [ 37. \hspace{0.25em} 38. \hspace{0.25em} 39.\hspace{0.25em}  40.] \\
   [ 41. \hspace{0.25em} 42. \hspace{0.25em} 43.\hspace{0.25em}  44.] \\
   [ 45. \hspace{0.25em} 46. \hspace{0.25em} 47.\hspace{0.25em}  48.]]
$

(d) 
$
[[  5., \hspace{0.25em}  6.],\\
 [ 21., \hspace{0.25em} 22.],\\
 [ 37., \hspace{0.25em} 38.]]
$

(e)
$
[[ 36.\hspace{0.25em}  35.] \\
 [ 40.\hspace{0.25em}  39.] \\
 [ 44.\hspace{0.25em}  43.] \\
 [ 48.\hspace{0.25em}  47.]]
$

Solution:

In [5]:
a = np.linspace(1,48,48).reshape(3,4,4)

print("Part (a)")
print(a[1,0,3])
print()

print("Part (b)")
print(a[0, 2])
print()

print("Part (c)")
print(a[2])
print()

print("Part (d)")
print(a[:,1,0:2])
print()

print("Part (e)")
print(a[2,:,3:1:-1])
print()

Part (a)
20.0

Part (b)
[ 9. 10. 11. 12.]

Part (c)
[[33. 34. 35. 36.]
 [37. 38. 39. 40.]
 [41. 42. 43. 44.]
 [45. 46. 47. 48.]]

Part (d)
[[ 5.  6.]
 [21. 22.]
 [37. 38.]]

Part (e)
[[36. 35.]
 [40. 39.]
 [44. 43.]
 [48. 47.]]



### 6.

Create two arrays by the codes:

`array1 = np.arange(20).reshape(4,5)`

`array2 = np.array([[1,2,np.nan],[4,5,6],[np.nan, 7, np.nan]])`

Test if elements in arrray1 and array2 are all evaluated to `True` by `np.all()`.

Test if any element in array1 and array 2 is evaluated to `True` by `np.any()`.

Then replace all the `np.nan` in array2 by the mean of array1. (Hint: use `np.isnan()` to test array2 first)



In [6]:
print("Part 1")
array1 = np.arange(20).reshape(4,5)
print(array1)
print()

array2 = np.array([[1,2,np.nan],[4,5,6],[np.nan, 7, np.nan]])
print(array2)
print()

print("Part 2")
print("For array1", np.all(array1)) 
print("For array2", np.all(array2))
print()

print("Part 3")
print("For array1", np.any(array1)) 
print("For array2", np.any(array2)) 
print()

print("Part 4")
print("The mean of array1 =", array1.mean())
array2isnan = np.isnan(array2)
print(array2isnan)
print()

for i in range(3):
    for j in range(3):
        if array2isnan[i][j] == True:
            array2[i][j] = array1.mean()

print(array2)

Part 1
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 1.  2. nan]
 [ 4.  5.  6.]
 [nan  7. nan]]

Part 2
For array1 False
For array2 True

Part 3
For array1 True
For array2 True

Part 4
The mean of array1 = 9.5
[[False False  True]
 [False False False]
 [ True False  True]]

[[1.  2.  9.5]
 [4.  5.  6. ]
 [9.5 7.  9.5]]


### 7.

a. Creat an array with 3 by 4 random numbers array within the range of (0, 1). Swap the three rows, that is, row index (0, 1, 2) -> row index (2, 0, 1). Swap first column and third column, that is, column index (0, 1, 2, 3) -> column index (2, 1, 0, 3)



In [7]:
print("Part 1")
# Create an array with 3 by 4 random numbers array within the range of (0, 1)
a = np.random.rand(3,4).reshape(3,4)
print(a)
print()

print("Part 2")
# Swap the three rows, that is, row index (0, 1, 2) -> row index (2, 0, 1)
a[[0, 1, 2]] = a[[2, 0, 1]]
print(a)
print()

print("Part 3")
# Swap first column and third column, that is, column index (0, 1, 2, 3) -> column index (2, 1, 0, 3)
a[:, [0, 1, 2, 3]] = a[:, [2, 1, 0, 3]]
print(a)
print()

Part 1
[[0.52243903 0.22406021 0.53017538 0.46273662]
 [0.02297151 0.41651362 0.94402413 0.60561552]
 [0.6030312  0.42412102 0.36669745 0.20700212]]

Part 2
[[0.6030312  0.42412102 0.36669745 0.20700212]
 [0.52243903 0.22406021 0.53017538 0.46273662]
 [0.02297151 0.41651362 0.94402413 0.60561552]]

Part 3
[[0.36669745 0.42412102 0.6030312  0.20700212]
 [0.53017538 0.22406021 0.52243903 0.46273662]
 [0.94402413 0.41651362 0.02297151 0.60561552]]



### 8.

Iris data is a prototype data set for machine learning beginners in building classfication models. It has five columns: sepallength, sepalwidth, petallength, petalwidth, and species. Data in the first four columns are float type data and the last column is string. Do the work below:

1. Use `genfromtxt()` to read data from the url `'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'` to a numpy array. 

2. Store the numeric values in one array and string values in the other array.

3. Calculate the mean, median, std of the first column, which is sepal length.

4. Normalize the data in the first columns, so that data are in the range of [0, 1]

5. the 5th and 95th percentile of iris's sepallength (the first column)


In [8]:
print("Part 1")
iris = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', 
                     delimiter=",", dtype = None, encoding = None)
print(iris)
# print(iris.shape) 150 rows
print()

print("Part 2")
a = iris.tolist() # convert to list
numerics = []
strings = []
for i in a:
    numerics.append(list(i[0:4]))
    strings.append(i[-1])
# Store the numeric values in one array and string values in the other array
num_ = np.array(numerics)
str_ = np.array(strings)
print(num_)
print(str_)
print()

print("Part 3")
mean = num_.mean(axis=0)
print('The mean of sepal length is', mean[0])
median = np.median(num_,axis=0)
print('The median of sepal length is', median[0])
std = num_.std(axis=0)
print('The std of sepal length is', std[0])
print()

# Part 4
print("Part 4")
max_val = num_.max(axis=0)
max_sepal_length = max_val[0]
min_val = num_.min(axis=0)
min_sepal_length = min_val[0]

normalized_num_ = np.copy(num_)
for i in range(150):
    x = normalized_num_[i][0]
    normalized_num_[i][0] = (x - min_sepal_length)/(max_sepal_length - min_sepal_length)
    
print(normalized_num_)
print()

# Part 5
N5_percentile = np.percentile(num_, 5, axis = 0)
print("The 5th percentile of sepal length is", N5_percentile[0])
N95_percentile = np.percentile(num_, 95, axis = 0)
print("The 95th percentile of sepal length is", N95_percentile[0])

Part 1
[(5.1, 3.5, 1.4, 0.2, 'Iris-setosa') (4.9, 3. , 1.4, 0.2, 'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, 'Iris-setosa') (4.6, 3.1, 1.5, 0.2, 'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, 'Iris-setosa') (5.4, 3.9, 1.7, 0.4, 'Iris-setosa')
 (4.6, 3.4, 1.4, 0.3, 'Iris-setosa') (5. , 3.4, 1.5, 0.2, 'Iris-setosa')
 (4.4, 2.9, 1.4, 0.2, 'Iris-setosa') (4.9, 3.1, 1.5, 0.1, 'Iris-setosa')
 (5.4, 3.7, 1.5, 0.2, 'Iris-setosa') (4.8, 3.4, 1.6, 0.2, 'Iris-setosa')
 (4.8, 3. , 1.4, 0.1, 'Iris-setosa') (4.3, 3. , 1.1, 0.1, 'Iris-setosa')
 (5.8, 4. , 1.2, 0.2, 'Iris-setosa') (5.7, 4.4, 1.5, 0.4, 'Iris-setosa')
 (5.4, 3.9, 1.3, 0.4, 'Iris-setosa') (5.1, 3.5, 1.4, 0.3, 'Iris-setosa')
 (5.7, 3.8, 1.7, 0.3, 'Iris-setosa') (5.1, 3.8, 1.5, 0.3, 'Iris-setosa')
 (5.4, 3.4, 1.7, 0.2, 'Iris-setosa') (5.1, 3.7, 1.5, 0.4, 'Iris-setosa')
 (4.6, 3.6, 1. , 0.2, 'Iris-setosa') (5.1, 3.3, 1.7, 0.5, 'Iris-setosa')
 (4.8, 3.4, 1.9, 0.2, 'Iris-setosa') (5. , 3. , 1.6, 0.2, 'Iris-setosa')
 (5. , 3.4, 1.6, 0.4, 'Iris-setosa') (5.2, 3